#! /bin/sh
### BEGIN INIT INFO
# Provides:          liveFolderSync
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Realtime Folder Syncronisation across servers
# Description:       Uses rsync and ssh to keep in sync a master and
#                    slave server, for example a web server.
### END INIT INFO

# Author: Tom Scott-Malden <tom@skywire.co.uk>
# Reference: http://www.thegeekstuff.com/2012/03/lsbinit-script/

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Realtime Folder Syncronisation across servers"
NAME=liveFolderSync
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/lock/subsys/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
INOTIFY=inotifywait

# Get function from functions library
. /etc/init.d/functions

#make sure files are there
test -x $DAEMON || exit 5

start() {
    echo -n "Starting $NAME: "
    #start daemons, perhaps with the daemon function
    $DAEMON &
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $PIDFILE
    return $RETVAL
}   

stop() {
    echo -n "Shutting down $NAME: "
    killproc $NAME -QUIT
    killproc $INOTIFY -QUIT
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $PIDFILE
    return $RETVAL
}

restart() {
    stop
    start
}

reload() {
    echo -n $"Reloading $NAME: "
    killproc $DAEMON -HUP
    RETVAL=$?
    echo
}
 
force_reload() {
    restart
}
 
rh_status() {
    status $NAME
}
 
rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart|configtest)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
